name: tasce_mobile
description: "TASCE Staff Mobile App"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.64.0
  collection: ^1.17.2
  onesignal_flutter: ^5.0.4
  # Essential UI packages
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  # State Management
  provider: ^6.1.2
  # Navigation
  go_router: ^13.2.0
  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  # Network
  dio: ^5.4.1
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.5
  package_info_plus: ^4.2.0
  # UI Components
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  # Authentication
  local_auth: ^2.2.0
  # PDF Generation and Printing
  pdf: ^3.10.8
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.8
  # App Icon
  flutter_launcher_icons: ^0.13.1
  # Splash Screen
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/tasce_r_logo.png
    - assets/images/tasce_logo_watermark.png
    - assets/images/ogun_logo.png
    - assets/images/icons/tasce_icon.png # Added this line
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true # Changed from "launcher_icon" to true
  ios: true
  image_path: "assets/images/icons/tasce_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icons/tasce_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icons/tasce_icon.png
  branding: assets/images/icons/tasce_icon.png
  color_dark: "#FFFFFF"
  image_dark: assets/images/icons/tasce_icon.png
  branding_dark: assets/images/icons/tasce_icon.png

  android_12:
    image: assets/images/icons/tasce_icon.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/icons/tasce_icon.png
    icon_background_color_dark: "#FFFFFF"

  web: false
